<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Stock Out Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            margin: 0;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .company-name {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 5px;
        }

        .report-meta {
            margin-bottom: 20px;
            color: #666;
        }

        .summary {
            margin-bottom: 30px;
            border: 1px solid #ddd;
            padding: 15px;
        }

        .summary-item {
            margin-bottom: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            font-size: 12px;
        }

        th,
        td {
            padding: 8px;
            border: 1px solid #ddd;
            text-align: left;
        }

        th {
            background-color: #f8f9fa;
        }

        .total-row {
            font-weight: bold;
            background-color: #f8f9fa;
        }

        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            padding: 10px;
            font-size: 10px;
            color: #666;
        }

        .page-break {
            page-break-after: always;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="company-name">{{ config('app.name') }}</div>
        <div>Stock Out Report</div>
        <div class="report-meta">
            Period: {{ $startDate->format('d/m/Y') }} - {{ $endDate->format('d/m/Y') }}<br>
            Report Generated: {{ now()->format('d/m/Y H:i') }}<br>
            Generated By: {{ auth()->user()->name }}
        </div>
    </div>

    <div class="summary">
        <div class="summary-item">
            <strong>Total Products:</strong> {{ number_format($summary['total_products']) }}
        </div>
        <div class="summary-item">
            <strong>Total Quantity:</strong> {{ number_format($summary['total_quantity']) }}
        </div>
        <div class="summary-item">
            <strong>Total Value:</strong> Rp {{ number_format($summary['total_value'], 0, ',', '.') }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Code</th>
                <th>Product</th>
                <th>Category</th>
                <th>Quantity</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($products as $product)
                <tr>
                    <td>{{ $product->product_code }}</td>
                    <td>{{ $product->product_name }}</td>
                    <td>{{ $product->category_name }}</td>
                    <td>{{ number_format($product->total_quantity) }}</td>
                    <td>Rp {{ number_format($product->total_value, 0, ',', '.') }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="3" style="text-align: right"><strong>Total:</strong></td>
                <td><strong>{{ number_format($summary['total_quantity']) }}</strong></td>
                <td><strong>Rp {{ number_format($summary['total_value'], 0, ',', '.') }}</strong></td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        {{ config('app.name') }} - Stock Out Report - Page {PAGE_NUM}/{PAGE_COUNT}
    </div>
</body>

</html>